name: datascience
dependencies:
- appnope
- cycler
- decorator
- freetype
- ipython
- ipython_genutils
- libpng
- matplotlib
- numpy
- openssl
- pandas
- path.py
- pexpect
- pickleshare
- pip
- pyparsing
- pyqt
- python
- python-dateutil
- python.app
- pytz
- qt
- readline
- scipy
- simplegeneric
- sip
- six
- sqlite
- tk
- traitlets
- wheel
- xz
- zlib
- pip:
  - alabaster
  - babel
  - coverage
  - coveralls
  - docopt
  - docutils
  - folium==0.2.1
  - ipython-genutils
  - jinja2
  - markupsafe
  - py
  - pygments
  - pytest
  - pyyaml
  - requests
  - setuptools
  - snowballstemmer
  - sphinx
  - sphinx-rtd-theme

